---
name: Test Campaign Name
network_env: mininet
topology:
  mininet:
    links:
      - name: 5g
        client_ip: 10.0.1.1/24
        server_ip: 10.0.1.2/24
        bw: 1000
        delay: 27.4ms
        loss: 0.1
      - name: 4g
        client_ip: 10.0.2.1/24
        server_ip: 10.0.2.2/24
        bw: 140
        delay: 29.2ms
        loss: 0.1
      # - name: wlan
      #   client_ip: 10.0.1.3/24
      #   server_ip: 10.0.2.2/24
      #   bw: 30
      #   delay: 20ms
      #   # loss: 0.7
  physical:
    client:
      hostname: client.example.com
      username: client_user
      password: client_password
      # ssh_key: /home/.ssh/
      store_location: /home

    server:
      hostname: server.example.com
      username: server_user
      password: server_password
      store_location: /home
schedulers:
  - name: ECFScheduler
    
  - name: MinRTTScheduler

  - name: FALCON
    params:
      train: 150
      param2: value2

  - name: RELES
    params:
      train: 150
      param2: value2

congestion_control:
  - olia
  - bbr
  - cubic
test:
  checkpoint: true
  server_debug: true
  num_iterations: 20
  file_size: 
    - 2M
    - 10M
    - 64M
results:
  dir: /path/to/results/directory
  plot:
    figsize:
      - 10
      - 6
    title: Throughput Distribution by Scheduler
    xlabel: Scheduler
    ylabel: Throughput (Mbps)
logging:
  file_level: DEBUG
  stdout_level: INFO
